version: '3'

services:
  rrcconfig:
    build: ./dockers/config/.
    volumes:    
      - ${GT_VOL_PATH}:/var/www/gt
      - ${SUBMITS_VOL_PATH}:/var/www/submits
      - ${SCRIPTS_VOL_PATH}:/code/scripts
      - ${VISUALIZATION_VOL_PATH}:/code/items/visualization/custom/
    ports:
      - "9010:80"
    restart: ${RESTART}
    networks:
      - rrc-net

  rrceval:
    build: ./dockers/python3.9/.
    volumes:    
      - ${GT_VOL_PATH}:/var/www/gt:ro
      - ${SUBMITS_VOL_PATH}:/var/www/submits:ro
      - ${SCRIPTS_VOL_PATH}:/code/scripts:ro
    ports:
      - "9020:80"
    restart: ${RESTART}
    networks:
      - rrc-net    

networks:
  rrc-net:
    name: rrcNet
    driver: bridge